development:
  adapter: postgresql
  encoding: unicode
  database: restauranteur_development
  pool: 5
  username: arkham
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: restauranteur_test
  pool: 5
  username: arkham
  password:
